export const products = [
    {
        id: 1,
        name: 'Product 1',
        price: 100,
        description: 'This is the first product',
        brand: 'Brand 1',
        category: 'Category 1',
        image: '/images/product1.jpg',
        rewiews: [],
    },
    {
        id: 2,
        name: 'Product 2',
        price: 200,
        description: 'This is the second product',
        brand: 'Brand 2',
        category: 'Category 2',
        image: '/images/product2.jpg',
        rewiews: [],
    },
    {
        id: 3,
        name: 'Product 3',
        price: 300,
        description: 'This is the third product',
        brand: 'Brand 3',
        category: 'Category 3',
        image: '/images/product3.jpg',
        rewiews: [],
    },
    {
        id: 4,
        name: 'Product 4',
        price: 400,
        description: 'This is the fourth product',
        brand: 'Brand 4',
        category: 'Category 4',
        image: '/images/product4.jpg',
        rewiews: [],
    },
    {
        id: 5,
        name: 'Product 5',
        price: 500,
        description: 'This is the fifth product',
        brand: 'Brand 5',
        category: 'Category 5',
        image: '/images/product5.jpg',
        rewiews: [],
    },
    {
        id: 6,
        name: 'Product 6',
        price: 600,
        description: 'This is the sixth product',
        brand: 'Brand 6',
        category: 'Category 6',
        image: '/images/product6.jpg',
        rewiews: [],
    },
    {
        id: 7,
        name: 'Product 7',
        price: 700,
        description: 'This is the seventh product',
        brand: 'Brand 7',
        category: 'Category 7',
        image: '/images/product7.jpg',
        rewiews: [],
    },
    {
        id: 8,
        name: 'Product 8',
        price: 800,
        description: 'This is the eighth product',
        brand: 'Brand 8',
        category: 'Category 8',
        image: '/images/product8.jpg',
        rewiews: [],
    },
    {
        id: 9,
        name: 'Product 9',
        price: 900,
        description: 'This is the ninth product',
        brand: 'Brand 9',
        category: 'Category 9',
    },
    {
        id: 10,
        name: 'Product 10',
        price: 1000,
        description: 'This is the tenth product',
        brand: 'Brand 10',
        category: 'Category 10',
        image: '/images/product10.jpg',
        rewiews: [],
    }
]